application: intern2015-findol
version: 1
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

#- url: /recommend/template
#  static_dir: recommend/template

- url: /.*
  script: _go_app
